import {chromium} from 'playwright';
import http from 'node:http'; import {readFileSync, existsSync, statSync} from 'node:fs'; import {join} from 'node:path';
const ROOT='/home/claude/ship/SHIP-2026-09-02j';
const srv=http.createServer((req,res)=>{ let p=decodeURIComponent(req.url.split('?')[0]); let f=join(ROOT,p); if(existsSync(f)&&statSync(f).isDirectory()) f=join(f,'index.html'); if(!existsSync(f)){res.writeHead(404);return res.end();} res.writeHead(200,{'Content-Type':f.endsWith('.html')?'text/html':'application/octet-stream'}); res.end(readFileSync(f)); }).listen(8770);
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome'});
const p=await b.newPage({viewport:{width:1400,height:900}}); p.on('pageerror',e=>console.log('PAGEERROR',e.message));
const reqs=[]; await p.route('https://nofilter-shared.netlify.app/**', r=>{ reqs.push(r.request().url().split('/').pop()); r.fulfill({status:200, body:''}); });
await p.goto('http://localhost:8770/',{waitUntil:'load'}); await p.waitForTimeout(1500);
const st=async(l)=>console.log(l.padEnd(28), await p.evaluate(()=>location.pathname+location.hash+' | '+window.__nfRoute+' | '+document.title.slice(0,40)+' | hero src: '+(document.querySelector('.cover-video')?.querySelector('source')?.getAttribute('src')||'-').split('/').pop()+' | hc:'+(window.__hc||0)));
await p.evaluate(()=>{ window.__hc=0; addEventListener('hashchange',()=>window.__hc++); });
await st('boot /');
await p.click('#nav a[data-r="shop"]'); await p.waitForTimeout(600); await st('click Shop');
await p.click('#nav a[data-r="origins"]'); await p.waitForTimeout(600); await st('click Origins');
await p.evaluate(()=>document.querySelector('.fbh-more[aria-controls="fbhd-gadis"]').click()); await p.waitForTimeout(700);
console.log('drawer via button:', await p.evaluate(()=>!document.getElementById('fbhd-gadis').hidden));
await p.goBack(); await p.waitForTimeout(600); await st('back');
await p.goBack(); await p.waitForTimeout(600); await st('back again');
await p.goForward(); await p.waitForTimeout(600); await st('forward');
await p.evaluate(()=>{ const a=document.querySelector('a[href="/origins"]'); a && a.click(); }); await p.waitForTimeout(600); await st('click href=/origins');
await p.goto('http://localhost:8770/#work',{waitUntil:'load'}); await p.waitForTimeout(1200); await st('load /#work');
await p.goto('http://localhost:8770/origins/batang-toru/',{waitUntil:'load'}); await p.waitForTimeout(1200); await st('load origin deep link');
console.log('toru drawer open:', await p.evaluate(()=>!document.getElementById('fbhd-toru').hidden), '| scrollY', await p.evaluate(()=>Math.round(scrollY)));
await p.click('#nav a[data-r="shop"]'); await p.waitForTimeout(600); await st('then Shop');
console.log('toru drawer now:', await p.evaluate(()=>!document.getElementById('fbhd-toru').hidden));
console.log('mp4 requested during session:', [...new Set(reqs.filter(x=>x.endsWith('.mp4')))].join(', '));
// file:// still hash
const q=await b.newPage(); q.on('pageerror',e=>console.log('PAGEERROR file',e.message)); await q.goto('file:///home/claude/nfw/Marketing/NoFilter-Website/NoFilter-Website-Master.html#shop',{waitUntil:'load'}); await q.waitForTimeout(1000);
console.log('file://', await q.evaluate(()=>location.hash+' | '+window.__nfRoute+' | '+document.title.slice(0,40)));
await q.click('#nav a[data-r="origins"]'); await q.waitForTimeout(500); console.log('file:// after click', await q.evaluate(()=>location.hash+' | '+window.__nfRoute));
await b.close(); srv.close();
